from api import db, Players, Dept

Players.query.delete()
Dept.query.delete()

dept1 = Dept(id=1, dName='IT')
dept2 = Dept(id=2, dName='Mech')
dept3 = Dept(id=3, dName='Elec')
dept4 = Dept(id=4, dName='SE')
dept5 = Dept(id=5, dName='Chemical')
dept6 = Dept(id=6, dName='BioMed')

p1 = Players(fname="Manu", lname="GK", position="goalkeeper", dept_id=1)
p2 = Players(fname="Fanny", lname="Gk", position="goalkeeper", dept_id=2)
p3 = Players(fname="Lola", lname="DF", position="defender", dept_id=1)
p4 = Players(fname="Abe", lname="DF", position="defender", dept_id=2)
p5 = Players(fname="Dube", lname="DF", position="defender", dept_id=3)
p6 = Players(fname="Ni", lname="MD", position="midfielder", dept_id=1)
p7 = Players(fname="Chang", lname="MD", position="midfielder", dept_id=2)
p8 = Players(fname="Meh", lname="MD", position="striker", dept_id=3)
p9 = Players(fname="Dude", lname="ST", position="striker", dept_id=1)
p10 = Players(fname="Sportsguy", lname="ST", position="", dept_id=2)
p11 = Players(fname="Sportsguys'sBrother", lname="MD", position="midfielder", dept_id=4)
p12 = Players(fname="Ranjit", lname="GK", position="goalkeeper", dept_id=4)
p13 = Players(fname="Kumal", lname="GK", position="goalkeeper", dept_id=5)
p14 = Players(fname="Dud", lname="DF", position="defender", dept_id=4)
p15 = Players(fname="Kman", lname="DF", position="defender", dept_id=5)
p16 = Players(fname="Malik", lname="DF", position="defender", dept_id=6)
p17 = Players(fname="Jman", lname="MD", position="midfielder", dept_id=5)
p18 = Players(fname="Q", lname="MD", position="midfielder", dept_id=6)
p19 = Players(fname="Pla", lname="ST", position="striker", dept_id=4)
p20 = Players(fname="Finally", lname="ST", position="striker", dept_id=5)

db.session.add_all([dept1, dept2, dept3, dept4, dept5, dept6, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20])
db.session.commit()